config/routes.rb
Rails.application.routes.draw do
    resources :users do
      get 'likes', to: 'users#likes'
      get 'followers', to: 'users#followers'
      get 'followees', to: 'users#followees'
      # delete 'followers/:id' => 'users#destroy'
    end
    resources :posts
    get 'buzzworthy', to: 'posts#buzzworthy'
    post 'buzzworthy', to: 'posts#buzzworthy'
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/login'
    get 'sessions/welcome'
    get '/likes' => 'likes#index'
    post '/likes' => 'likes#toggle_like'
    post '/followers' => 'followers#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'welcome', to: 'sessions#welcome'
    get 'authorized', to: 'sessions#page_requires_login'
    post '/logout' => 'sessions#destroy'
    # delete '/followers/:id' => 'followers#destroy'
    post '/users/:id/follow', to: "users#follow", as: "follow_user"
    post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  # resources :users do
  #   get 'likes', to: 'users#likes'
  # end
  # resources :posts
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/welcome'
  # get '/likes' => 'likes#index'
  # post '/likes' => 'likes#toggle_like'
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # get 'welcome', to: 'sessions#welcome'
  # get 'authorized', to: 'sessions#page_requires_login'
  # post '/logout' => 'sessions#destroy'

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
    has_secure_password
    validates :user_name, uniqueness: { case_sensitive: true }
    validates :user_name, presence: true
    validates :name, presence: true
    validates :location, presence: true
    validates :bio, presence: true

    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users
    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users
    

    def liked?(post)
        self.likes.find_by(post_id: post.id)
    end

    # def follows?(user_id)
    #     f = self.followers.find {|follower| follower.followee_id == user_id}
    #     if f == nil
    #         true
    #     else
    #         false
    #     end
    # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
        render :new, layout: 'login'
    end 

    def followers
        @user = User.find(params[:user_id])
    end 
    
    def followees
        @user = User.find(params[:user_id])
    end 

    def create 
        @user = User.create(user_params(:user_name, :name, :password, :location, :bio))
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to '/posts'
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit
        @user = User.find(params[:id])
        if current_user.id == @user.id 
            @user 
        else  
            redirect_to user_path(@user)
        end
    end 

    def update
        @user = current_user
        @user.update(user_params(:user_name, :name, :password, :location, :bio))
        redirect_to user_path(current_user)
    end

    def likes
        @user = User.find(params[:user_id])
    end

    def follow
        @user = User.find(params[:id])
        current_user.followees << @user
        redirect_to user_path(@user)
    end

    def unfollow
        @user = User.find(params[:id])
        current_user.followed_users.find_by(followee_id: @user.id).destroy
        redirect_to user_path(@user)
    end

    #should we let users delete their accounts?
    
    private

    def user_params(*args)
        params.require(:user).permit(*args)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<h1> Edit Profile</h1>

<%= form_for @user do |f|%>
    <section class="left"> <%= f.label 'Name'%> </section>
   <section class="right"> <%= f.text_field :name %> </section>
    <section class="left"> <%= f.label 'Username'%> </section>
   <section class="right">  <%= f.text_field :user_name %> </section>
   <section class="left">  <%= f.label 'Password'%> </section>
   <section class="right">  <%= f.password_field :password %> </section>
   <section class="left">  <%= f.label 'Location'%> </section>
    <section class="right"> <%= f.text_field :location %></section>
    <%= f.submit 'Update Account', id: "submit" %>
<% end %>

app/views/users/followees.erb
<h1 id="follower-page-title">Who <%= @user.name %> is Following</h1>

<% if @user.followees.count > 0 %>
    <h5 id="followee-count"><%= @user.followees.count %> Bee(s) 🐝</h5>
    <% @user.followees.each do |followee| %>
            <section class="user-name"><%= link_to "@#{followee.user_name}", user_path(followee) %></section>
    <% end %>
<% else%>
    <p><%= @user.name %> is not following anyone!</p>
<% end %>

app/views/users/followers.erb
<h1 id="follower-page-title"><%= @user.name %>'s Followers</h1>

<% if @user.followers.count > 0 %>
    <h5 id="follower-count"><%= @user.followers.count %> Bee(s) 🐝</h5>
    <% @user.followers.each do |follower| %>
            <section class="user-name"><%= link_to "@#{follower.user_name}", user_path(follower) %></section>
    <% end %>
<% else%>
    <p><%= @user.name %> does not have any followers!</p>
<% end %>

app/views/users/likes.erb
<h1 id="likes-page-title"><%= @user.name %>'s Likes</h1>

<% if @user.likes.count > 0 %>
    <% @user.likes.feed_order.each do |like| %>
        <div class="post-container">
            <section class="user-name"><%= link_to "@#{like.post.user.user_name}", user_path(like.post.user) %></section>
            <section class="post-content"><%= like.post.content %></section>
            <div class="time-likes-container">
                <section class="time-posted"><%= like.post.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %B %d, %Y, %l:%M %p") %> </section>
            </div>
        </div>
    <% end %>
<% else%>
    <p><%= @user.name %> does not have any likes!</p>
<% end %>

app/views/users/new.erb
<h1>Join the Hive</h1>

<% if flash[:errors] %>
<% flash[:errors].each do |error|%>
        <section class="error-message"><%= error %> </section>
    <% end %>
<% end %>

<div class="form-container">
    <%= form_for @user do |f|%>
        <section class="label"> <%= f.label 'Name'%> </section>
        <section class="field"> <%= f.text_field :name %> </section>
        <section class="label"> <%= f.label 'Username'%> </section>
        <section class="field"> <%= f.text_field :user_name %> </section>
        <section class="label"> <%= f.label 'Password'%> </section>
        <section class="field"> <%= f.password_field :password %> </section>
        <section class="label"> <%= f.label 'Location'%> </section>
        <section class="field"> <%= f.text_field :location %> </section>
        <section class="label"> <%= f.label 'Bio'%> </section>
        <section class="field"> <%= f.text_field :bio %> </section>
        <section class="submit"> <%= f.submit 'Create Account' %> </section>
    <% end %>
</div>

app/views/users/show.erb
<div id="name-logout-container">
    <section id="following-name-container">
        <h1><%= @user.name %>'s Profile</h1>
        <%= link_to "#{@user.followers.count} Followers", user_followers_path(@user) %>
        <%= link_to "#{@user.followees.count} Following", user_followees_path(@user) %>
    </section>
    <section id="all-links">
        <% if @user.id == current_user.id %>
            <%= button_to "Logout", '/logout', method: :post %>
        <% else %>
            <% if current_user.followees.include?(@user) %>
                <h5><%= button_to "Unfollow", unfollow_user_path, method: "POST" %></h5>
            <% else %>
                <h5><%= button_to "Follow", follow_user_path, method: "POST"  %></h5>
            <% end %>
        <% end%>
    </section>
</div>


<div class="row-container">
    <section class="left-column"> USERNAME </section>
    <section class="right-column"> <%= @user.user_name.upcase %> </section>
    <section class="left-column"> LOCATION</section>
    <section class="right-column"> <%= @user.location.upcase %> </section>
    <section class="left-column"> BIO </section>
    <section class="right-column"> <%= @user.bio.upcase %> </section>
</div>


<% if @user.id == current_user.id %>
    <div id="edit-user"><%= link_to '<button type="button">Edit Profile</button>'.html_safe, edit_user_path %></div>
<% end %>

<hr>

<% if @user == current_user %>

    <%= form_tag ({controller: 'posts',
        action: 'create',
        method: 'post'}), :id => "create-buzz" do %>
    <p id="buzz-prompt">Create some buzz</p>
    <%= text_area_tag :content %> 
    <%= submit_tag "Buzz it up", :id => "submit"%>
    <% end %>
    <hr>
<%end %>

<div id="profile-feed-container">
    <h2> <%= @user.name%>'s Buzz </h2>
    <%= link_to '<button type="button">View Likes</button>'.html_safe, user_likes_path(@user) %>
</div>
<% @user.posts.feed_order.each do |post| %>
    <div class="post-container">
        <section class="edit-delete-container">
            <% if @user.id == current_user.id %>
            <%= link_to 'Edit Post', edit_post_path(post) %> |
            <%= link_to 'Delete Post', post_path(post), method: :delete %>
            <% end %>
        </section>

        <section class="post-content">
            <%= post.content %>
        </section>

        <div class="time-likes-container">
            <section class="time-posted"><%= post.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %B %d, %Y, %l:%M %p") %> </section>
            <section class="bee-button-likes">
                <%= post.likes.count%>
                <%= form_tag ({controller: 'likes',
                    action: 'toggle_like',
                    method: 'post'}) do %>
                    <input type=hidden name=post_id value="<%= post.id %>">
                    <input type=submit class="bee-emoji" value='🐝'>
                <% end %>
            </section>
        </div>
</div>
<% end %>