config/routes.rb
Rails.application.routes.draw do
    resources :users do
      get 'likes', to: 'users#likes'
      get 'followers', to: 'users#followers'
      get 'followees', to: 'users#followees'
      # delete 'followers/:id' => 'users#destroy'
    end
    resources :posts
    get 'buzzworthy', to: 'posts#buzzworthy'
    post 'buzzworthy', to: 'posts#buzzworthy'
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/login'
    get 'sessions/welcome'
    get '/likes' => 'likes#index'
    post '/likes' => 'likes#toggle_like'
    post '/followers' => 'followers#create'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'welcome', to: 'sessions#welcome'
    get 'authorized', to: 'sessions#page_requires_login'
    post '/logout' => 'sessions#destroy'
    # delete '/followers/:id' => 'followers#destroy'
    post '/users/:id/follow', to: "users#follow", as: "follow_user"
    post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  # resources :users do
  #   get 'likes', to: 'users#likes'
  # end
  # resources :posts
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/welcome'
  # get '/likes' => 'likes#index'
  # post '/likes' => 'likes#toggle_like'
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # get 'welcome', to: 'sessions#welcome'
  # get 'authorized', to: 'sessions#page_requires_login'
  # post '/logout' => 'sessions#destroy'

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user 
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes
    validates :content, length: { in: 1..300 }

    def self.feed_order
        self.order(created_at: :desc)
    end

    def self.like_order
        self.all.sort_by { |post|
            post.likes.count
        }.reverse.first(5)
    end
        
    #     likes_ordered = like_count_ordered(likes_grouped)
    #     top_five = likes_ordered.first(5)
    # end

    # def like_count_ordered(likes)
    #     likes.order(:desc)
    # end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        followee_posts = []
        current_user.followees.each do |followee| 
            followee.posts.each do |post|
              followee_posts << post  
            end
        end

        # this is solely if we want the current users posts to also be in their feed
        current_user.posts.each do |post|
            followee_posts << post 
        end

        @posts = followee_posts.sort_by { |post| post[:created_at] }.reverse
    end

    def buzzworthy
        @posts = Post.all
    end

    def create
        @post = Post.create(content: params[:content], user_id: current_user.id)
        redirect_back fallback_location: posts_path
    end

    def edit
        @post = Post.find(params[:id])
        if @post.user_id == current_user.id 
            @post
        else  
            redirect_back fallback_location: posts_path
        end
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params(:content, current_user.id))
        redirect_to user_path(current_user)
    end

    def destroy
        @post = Post.find(params[:id])
       if @post.user_id == current_user.id 
            @post.destroy 
       end
        redirect_to user_path(current_user)
    end

    private

    def post_params(*args)
        params.require(:post).permit(*args)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/buzzworthy.erb
<h1>What's Buzzworthy</h1>

<% @posts.like_order.each do |post|%>
    <div class="post-container">
    <section class="user-name"><%= link_to "@#{post.user.user_name}", user_path(post.user_id), class: "user-link" %> </section>

    <section class="post-content"><%=post.content%></section>

    <div class="time-likes-container">
        <section class="time-posted"><%= post.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %B %d, %Y, %l:%M %p") %> </section>
        <section class="bee-button-likes">
            <%= post.likes.count%>
            <%= form_tag ({controller: 'likes',
                action: 'toggle_like',
                method: 'post'}) do %>
                    <input type=hidden name=post_id value="<%= post.id %>">
                    <input type=hidden name=user_id value="<%= post.user_id %>">
                    <input type=submit class="bee-emoji" style="border:0; text-decoration:none; outline:none" value='🐝'>
            <% end %>

        </section>
    </div>
    </div>
<%end%>

app/views/posts/edit.erb
<h1>Edit Buzz</h1>
<section id="post-container">
<%= form_for @post do |f| %>
    <%= f.label "Change your buzz" %>...<br>
    <%= f.text_area :content, id: "content" %><br>
    <section> <%= f.submit id: "submit" %> </section>
<% end %>
</section>

app/views/posts/index.erb
<div class="feed-header-container">
    <h1 id="feed-title">Buzz Feed</h1>
    <%= link_to '<button type="button">What\'s Buzzworthy</button>'.html_safe, buzzworthy_path %>
</div>

    

    <%= form_tag ({controller: 'posts',
        action: 'create',
        method: 'post'}), :id => "create-buzz" do %>
    <p id="buzz-prompt">Stir the honey pot...</p>
    <%= text_area_tag :content %> 
    <%= submit_tag "Buzz it up", :id => "submit"%>
    <% end %>
    <hr>

<% @posts.each do |post|%>
    <div class="post-container">
    <section class="user-name"><%= link_to "@#{post.user.user_name}", user_path(post.user_id), class: "user-link" %> </section>

    <section class="post-content"><%=post.content%></section>

    <div class="time-likes-container">
        <section class="time-posted"><%= post.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %B %d, %Y, %l:%M %p") %> </section>
        <section class="bee-button-likes">
            <%= post.likes.count%>
            <%= form_tag ({controller: 'likes',
                action: 'toggle_like',
                method: 'post'}) do %>
                    <input type=hidden name=post_id value="<%= post.id %>">
                    <input type=submit class="bee-emoji" style="border:0; text-decoration:none; outline:none" value='🐝'>
            <% end %>

        </section>
    </div>
    </div>
<%end%>